name: NestJS CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.19.1' # or another version if needed
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Connect to EC2 and Deploy
      run: |
           ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s'  ~/./scripts/deploy_njsp.sh
      env: 
        EC2_USER: ec2-user # or ubuntu, depending on your AMI
