name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
   
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to EC2
      run: |
        scp -r ./nest-hello-world ec2-user@98.130.36.134:/home/ubuntu/nest-hello-world

        ssh ec2-user@98.130.36.134 << 'ENDSSH' cd /home/ubuntu/nest-hello-world
        npm install
        npm start
        ENDSSH
 
